apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.STATEFULSET.LABEL }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.STATEFULSET.REPLICAS }}
  selector:
    matchLabels:
      app: {{ .Values.STATEFULSET.LABEL }}
  serviceName: {{ .Values.SERVICE.NAME }}
  template:
    metadata:
      namespace: {{ .Release.Namespace }}
      labels:
        app: {{ .Values.STATEFULSET.LABEL }}
    spec:
      containers:
#        - args:
#            - '--dbpath'
#            - /data/db
#          command:
#            - mongod
#            - '--bind_ip_all'
#            - '--replSet'
#            - rs0
        - name: {{ .Values.STATEFULSET.CONTAINER.NAME }}
          imagePullPolicy: {{ .Values.IMAGE.PULL_POLICY }}
          
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}
          image: {{ .Values.IMAGE.VERSION }}
          volumeMounts:
            - mountPath: {{ .Values.PERSISTENCE.PATH }}
              name: {{ .Values.PERSISTENCE.PVC_NAME }}
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: {{ .Values.PERSISTENCE.PVC_NAME }}
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.PERSISTENCE.SIZE }}

      {{ if .Values.STATEFULSET.TOLERATIONS.ENABLED }}
      tolerations:
      - key: {{ .Values.STATEFULSET.TOLERATIONS.KEY }}
        operator: {{ .Values.STATEFULSET.TOLERATIONS.OPERATOR }}
        value: {{ .Values.STATEFULSET.TOLERATIONS.VALUE }}
        effect: {{ .Values.STATEFULSET.TOLERATIONS.EFFECT }}
      {{ end }}
      {{ if .Values.STATEFULSET.NODESELECTOR.ENABLED }}
      nodeSelector:
        {{ .Values.STATEFULSET.NODESELECTOR.KEY }}: {{ .Values.STATEFULSET.NODESELECTOR.VALUE }}
        {{ end }}