{{ if .Values.INIT.ENABLED }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.PERSISTENCE.PVC_NAME }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.PERSISTENCE.SIZE }}
  storageClassName: {{ .Values.PERSISTENCE.STORAGECLASS }}
  {{- end }}
  
---
{{ if .Values.INIT.ENABLED }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{{ .Values.PERSISTENCE.PVC_NAME }}-pv"
spec:
  capacity:
    storage: {{ .Values.PERSISTENCE.SIZE }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.PERSISTENCE.STORAGECLASS }}
  hostPath:
    path: /mnt/data
  {{- end }}

