IMAGE:
  VERSION: "mongo:8.0.1"
  PULL_POLICY: IfNotPresent

DEPLOYMENT:
  REPLICAS: 1
  PORT: 27017
  TOLERATIONS:
    ENABLED: false
    KEY: application
    OPERATOR: Equal
    VALUE: mongodb
    EFFECT: NoSchedule
  NODESELECTOR:
    ENABLED: false
    KEY: application
    VALUE: mongodb

SERVICE:
  TYPE: ClusterIP
  PORT: 27017
  LOAD_BALANCER:
    ENABLED: false
    DNS_SUFFIX: db.snackbar.com.br

HPA:
  ENABLED: true
  MAXREPLICAS: 2
  CPU: 90
  MEMORY: 800Mi

INIT:
  ENABLED: true


PERSISTENCE:
  ENABLED: true
  SIZE: 8Gi
  STORAGECLASS: standard
  PATH: /data/db
  VOLUME_NAME: mongo-data
  PVC_NAME: mongo-pvc

SECRET:
  MONGO_INITDB_ROOT_USERNAME: root
  MONGO_INITDB_ROOT_PASSWORD: rootpassword
  MONGODB_USER: snackbaruser
  MONGODB_PASSWORD: snack01
  MONGO_INITDB_DATABASE: snackbar
  DB_HOST: snackbar-mongo-db.ns-snackbar.svc.cluster.local


