{{ if .Values.INIT.ENABLED }}
apiVersion: batch/v1
kind: Job
metadata:
  name: init-mongo-job
spec:
  template:
    metadata:
      name: init-mongo
      annotations:
        "helm.sh/hook": "pre-install"
        "helm.sh/hook-delete-policy": "hook-succeeded"
    spec:
    
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.IMAGE.VERSION }}
          command:
            - /bin/bash
            - "-c"
            - "cp /scripts/init-mongo.sh /tmp/init-mongo.sh && chmod +x /tmp/init-mongo.sh && /tmp/init-mongo.sh"
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}
          volumeMounts:
            - name: init-script
              mountPath: /scripts
      restartPolicy: OnFailure 
      volumes:
        - name: init-script
          configMap:
            name: init-mongo-script
      {{ if .Values.STATEFULSET.TOLERATIONS.ENABLED }}
      tolerations:
      - key: {{ .Values.STATEFULSET.TOLERATIONS.KEY }}
        operator: {{ .Values.STATEFULSET.TOLERATIONS.OPERATOR }}
        value: {{ .Values.STATEFULSET.TOLERATIONS.VALUE }}
        effect: {{ .Values.STATEFULSET.TOLERATIONS.EFFECT }}
      {{ end }}
      {{ if .Values.STATEFULSET.NODESELECTOR.ENABLED }}
      nodeSelector:
        {{ .Values.STATEFULSET.NODESELECTOR.KEY }}: {{ .Values.STATEFULSET.NODESELECTOR.VALUE }}
        {{ end }}
{{ end }}
