apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.PERSISTENCE.PVC_NAME }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.PERSISTENCE.SIZE }}
