name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - homolog
      - feature/eks

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: ./backend
        file: Dockerfile
        push: true
        tags: 171219910203199431032017/snackbar:latest

    - name: Docker logout
      run: docker logout
